import os
import sys
import time
import subprocess
from datetime import datetime

from Zetong_old_code.log_writer0 import init_log, write_log
from robot_interface_wrapper import ROB_INF as ROB_INF


# ============================================================
# Basic configuration
# ============================================================

PROJECT_ROOT = r"D:\Acoustics"

RECORD_SCRIPT = os.path.join(
    PROJECT_ROOT,
    "EConMateSense",
    "record_signal_two_channel.py"
)

INFERENCE_SCRIPT = os.path.join(
    PROJECT_ROOT,
    "EConMateSense",
    "two_channel_inference.py"
)

ROBOT_IP = "192.168.1.100"

FLAG_GROUP = 5
FLAG_INDEX = 0

CHECK_INTERVAL = 0.1


# ============================================================
# Robot connection
# ============================================================

def connect(ip_address):
    if ip_address == "":
        raise Exception("Robot IP not defined")

    RI = ROB_INF(ip_address)
    RI.connect()

    return RI


# ============================================================
# Flag handling
# ============================================================

def is_pre_position_flag_active(flag):
    """
    Decide whether the robot has reached the pre-position.

    This function is intentionally written to support different possible
    return formats from get_flag().

    Supported active values:
        True
        1
        (True, 1)

    If your robot interface returns another value for pre-position,
    modify this function only.
    """

    if flag is True:
        return True

    if flag == 1:
        return True

    if flag == (True, 1):
        return True

    return False


# ============================================================
# Subprocess handling
# ============================================================

def run_script_blocking(script_path, script_name):
    """
    Run one Python script and wait until it finishes.

    This is important:
    - recording must finish before inference starts
    - inference must use the latest_recording.json generated by recording
    """

    if not os.path.exists(script_path):
        print(f"[ERROR] {script_name} not found:")
        print(script_path)
        return False

    print("\n----------------------------------------")
    print(f"Starting {script_name}")
    print(f"Script: {script_path}")
    print("----------------------------------------")

    start_time = datetime.now()

    try:
        result = subprocess.run(
            [sys.executable, script_path],
            cwd=PROJECT_ROOT,
            check=True
        )

        end_time = datetime.now()
        duration = (end_time - start_time).total_seconds()

        print("----------------------------------------")
        print(f"{script_name} finished successfully.")
        print(f"Duration: {duration:.2f} s")
        print("----------------------------------------")

        return True

    except subprocess.CalledProcessError as e:
        print("----------------------------------------")
        print(f"[ERROR] {script_name} failed.")
        print(f"Return code: {e.returncode}")
        print("----------------------------------------")

        return False

    except Exception as e:
        print("----------------------------------------")
        print(f"[ERROR] Unexpected error while running {script_name}: {e}")
        print("----------------------------------------")

        return False


# ============================================================
# Logging
# ============================================================

def safe_get_force_z(force):
    """
    Extract force[2] safely.
    If force is not available, return None.
    """

    try:
        return round(force[2], 2)
    except Exception:
        return None


def write_trigger_log(force_z):
    """
    Write trigger information to the existing CSV log.

    The online system does not know the true plug type or noise condition
    before CNN inference, so interface and noise_env are set to online/unknown.
    """

    try:
        write_log(
            noise_env="online_unknown",
            interface="online_unknown",
            force_third=force_z
        )

        print(f"[LOG] Trigger logged. Force Z: {force_z}")

    except Exception as e:
        print(f"[WARNING] Failed to write log: {e}")


# ============================================================
# One complete detection cycle
# ============================================================

def run_detection_cycle(force_z):
    """
    One complete online detection cycle:

    1. Record two-channel audio for 5 s
    2. Save latest_recording.json
    3. Run two-channel CNN inference
    4. Output final decision
    """

    cycle_start = datetime.now()

    print("\n==================================================")
    print("ONLINE DETECTION CYCLE STARTED")
    print("Time:", cycle_start.strftime("%Y-%m-%d %H:%M:%S"))
    print("Force Z at trigger:", force_z)
    print("==================================================")

    # Step 1: two-channel recording
    recording_ok = run_script_blocking(
        RECORD_SCRIPT,
        "record_signal_two_channel.py"
    )

    if not recording_ok:
        print("[ERROR] Recording failed. Inference will be skipped.")
        return False

    # Step 2: two-channel inference
    inference_ok = run_script_blocking(
        INFERENCE_SCRIPT,
        "two_channel_inference.py"
    )

    if not inference_ok:
        print("[ERROR] Inference failed.")
        return False

    cycle_end = datetime.now()
    cycle_duration = (cycle_end - cycle_start).total_seconds()

    print("\n==================================================")
    print("ONLINE DETECTION CYCLE FINISHED")
    print("Time:", cycle_end.strftime("%Y-%m-%d %H:%M:%S"))
    print(f"Total duration: {cycle_duration:.2f} s")
    print("==================================================")

    return True


# ============================================================
# Main control loop
# ============================================================

def main():
    print("Initializing log file...")
    init_log()

    print("Connecting to robot...")
    r2_ri = connect(ROBOT_IP)
    print("Robot connected.")

    print("\nCentral control with inference is running.")
    print("Waiting for pre-position flag...")
    print(f"Flag group: {FLAG_GROUP}, Flag index: {FLAG_INDEX}")

    system_armed = True

    try:
        while True:
            flag = r2_ri.get_flag(FLAG_GROUP, FLAG_INDEX)
            force = r2_ri.get_force()
            force_z = safe_get_force_z(force)

            pre_position_active = is_pre_position_flag_active(flag)

            # ------------------------------------------------
            # Rising edge trigger:
            # Start one detection cycle only once when flag becomes active.
            # ------------------------------------------------
            if pre_position_active and system_armed:
                print("\n[TRIGGER] Pre-position flag detected.")
                print(f"Flag value: {flag}")
                print(f"Force Z: {force_z}")

                system_armed = False

                write_trigger_log(force_z)

                run_detection_cycle(force_z)

                print("\nWaiting for flag reset before next cycle...")

            # ------------------------------------------------
            # Reset condition:
            # The system is armed again only after flag becomes inactive.
            # ------------------------------------------------
            elif not pre_position_active and not system_armed:
                print("\n[RESET] Pre-position flag reset.")
                print("System armed for next detection cycle.")

                system_armed = True

            time.sleep(CHECK_INTERVAL)

    except KeyboardInterrupt:
        print("\nProgram manually terminated.")
        print("Central control stopped.")

    except Exception as e:
        print("\n[ERROR] Central control stopped because of an exception:")
        print(e)


if __name__ == "__main__":
    main()